name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        working-directory: ./package
        run: npm ci
      - name: Build package
        working-directory: ./package
        run: npm run build
      - name: Publish to npm registry
        working-directory: ./package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
